#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BillList.Resource", IsApplication=true)]

namespace BillList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DAL.Resource.String.ApplicationName = global::BillList.Resource.String.ApplicationName;
			global::DAL.Resource.String.Hello = global::BillList.Resource.String.Hello;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int planets_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int addBillBtn = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int billNameTextBox = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int costInput = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int dayOfMonthSeekBar = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int dayOfMonthTextView = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int linearLayout1 = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int monthlabellabel = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int numberPicker1 = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int spinner = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int statusLbl = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int statusTxtView = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int viewListBtn = 2131165195;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddBill = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int month_prompt = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
